import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const gilroyLight = localFont({
  src: "./fonts/Gilroy-Light.woff",
  variable: "--font-gilroy-light",
  weight: "100",
});
const gilroyExtraBold = localFont({
  src: "./fonts/Gilroy-ExtraBold.woff",
  variable: "--font-gilroy-extra-bold",
  weight: "900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gilroyLight.variable} ${gilroyExtraBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
